#!/usr/local/bin/php
<?php
echo("Sleeping for 10 seconds. To ensure that rabbitmq already started\n");
sleep(10);
require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;
$connection = new AMQPStreamConnection('rabbitmq', 5672, 'guest', 'guest');
$channel = $connection->channel();
$channel->queue_declare('mychannel', false, false, false, false);
$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'mychannel');
echo " [x] Sent 'Hello World!'\n";
$channel->close();
$connection->close();
